In [2]:
# Q 1:- Creat a numpy array'arr' of integers from 0 to 5 and print its data type.
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.dtype

dtype('int32')

In [9]:
# Q 2:- Given a numpy array 'arr', check if its data type is floot64.
arr = np.array([1.5,2.6,3.7])

In [10]:
arr.dtype

dtype('float64')

In [11]:
# Q 3 :- create a numpy 'arr' with a data type of complex128 containing three complex numbers
arr = np.array([1+2j,2+3j,3+4j])

In [13]:
arr.dtype

dtype('complex128')

In [16]:
# Q 4:- convert an existing numpy array 'arr' of integers to floot32 data type
arr = np.array([1,2,3,4])
arr = arr.astype(float)

In [17]:
arr

array([1., 2., 3., 4.])

In [19]:
arr.dtype

dtype('float64')

In [24]:
# Q 5 :- given a numpy 'arr' with floot64 data type, convert it to floot32 to reduce decimal precision
arr = np.array([1.234567,2.345678], dtype = np.float64)

In [25]:
arr.dtype

dtype('float64')

In [30]:
arr = arr.astype(np.float32)

In [31]:
arr.dtype

dtype('float32')

In [42]:
# Q 6 :- white a function array_attributes that takes a numpy array as input and returns its shape, siz and data type

In [46]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print(f"Shape: {shape}, Size: {size}, Data type: {dtype}")

Shape: (2, 3), Size: 6, Data type: int32


In [48]:
# Q 7 :- create a function array_dimension that tales a numpy array as iput and returns its dimensionality
def array_dimenion(arr):
    return arr.ndim

In [49]:
arr = np.array([[1,2,3],[4,5,6]])
dim = array_dimenion(arr)
print(f"dimenion {dim}")

dimenion 2


In [54]:
# Q 8 :- Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

In [55]:
arr = np.array([[1, 2], [3, 4]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print(f"Item size: {item_size} bytes, Total size: {total_size} bytes")


Item size: 4 bytes, Total size: 16 bytes


In [56]:
# Q 9:-  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def item_size_info(arr):
    return arr.shape, arr.strides

In [57]:
arr = np.array([[1,2],[3,4]])
shap, strides = item_size_info(arr)
print(f"shap: {shap}, strides{strides}")

shap: (2, 2), strides(8, 4)


In [58]:
# Q 10:-  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides


In [59]:
arr = np.array([[1, 2], [3, 4]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}, Strides: {strides}")

Shape: (2, 2), Strides: (8, 4)


In [1]:
# Q 11:-  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)


In [2]:
arr = create_zeros_array(5)
arr

array([0., 0., 0., 0., 0.])

In [3]:
# Q 12 :- Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled
#with ones of size `rows x cols`.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [4]:
matrix = create_ones_matrix(3, 4)
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Q 13 :- Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPyarray
#with a range starting from `start`, ending at stop (exclusive), and with the specified step`.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [6]:
arr = generate_range_array(2, 10, 2)
print(arr)

[2 4 6 8]


In [9]:
# Q 14:-  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generatesa NumPy
#array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [10]:
arr = generate_linear_space(0.0, 1.0, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
# Q 15:-  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n`
#using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

In [12]:
identity = create_identity_matrix(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# Q 16:-  Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(lst):
    return np.array(lst)

In [14]:
my_list = [1, 2, 3, 4]
arr = list_to_array(my_list)
print(arr)

[1 2 3 4]


In [15]:
# Q 17:- Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
original_array = np.array([10, 20, 30, 40])

view_array = original_array.view()

print("Original Array:")
print(original_array)

print("\nView Array:")
print(view_array)

Original Array:
[10 20 30 40]

View Array:
[10 20 30 40]


In [16]:
# Q 18 :-  Write a function that takes two NumPy arrays and concatenates them along a specified axis
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = concatenate_arrays(a, b, axis=0)
print("Concatenated along axis 0:\n", result)

result = concatenate_arrays(a, b, axis=1)
print("\nConcatenated along axis 1:\n", result)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [18]:
# Q 19:- Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6, 7],
                 [8, 9, 10]])

# Concatenate horizontally (axis=1)
result = np.concatenate((arr1, arr2), axis=1)

print("Result of horizontal concatenation:")
print(result)

Result of horizontal concatenation:
[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [19]:
# Q 20:- Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays):
    return np.vstack(arrays)

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Stack vertically
result = vertical_stack([a, b, c])

print("Vertically stacked array:")
print(result)


Vertically stacked array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Q 21:-  Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

In [22]:
arr = create_range_array(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [23]:
# Q 22:-Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_equally_spaced_array():
    return np.linspace(0, 1, 10)

In [24]:
arr = generate_equally_spaced_array()
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [25]:
# Q 23:- . Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def generate_log_spaced_array():
    return np.logspace(0, 3, 5) 

In [26]:
arr = generate_log_spaced_array()
print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [27]:
# Q 24:-Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import numpy as np
import pandas as pd

def create_random_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    
    df = pd.DataFrame(data, columns=['Column 1', 'Column 2', 'Column 3'])
    
    return df

In [28]:
df = create_random_dataframe()
print(df)

   Column 1  Column 2  Column 3
0        61        31        54
1        91        59        98
2        61        50        21
3        14         9        99
4        70        27        18


In [29]:
# Q 25:- Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations
#within the Pandas DataFrame.
import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


In [30]:
data = {'Column 1': [10, -5, 30, -1, 45],
        'Column 2': [-3, 25, 100, -7, 0]}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negatives_with_zero(df, 'Column 1')

print("\nDataFrame after replacing negatives in 'Column 1' with zero:")
print(df)


Original DataFrame:
   Column 1  Column 2
0        10        -3
1        -5        25
2        30       100
3        -1        -7
4        45         0

DataFrame after replacing negatives in 'Column 1' with zero:
   Column 1  Column 2
0        10        -3
1         0        25
2        30       100
3         0        -7
4        45         0


In [31]:
#Q 26:- Access the 3rd element from the given NumPy array.   
        #arr = np.array([10, 20, 30, 40, 50])
arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]
print(third_element)

30


In [32]:
# Q 27:-  Retrieve the element at index (1, 2) from the 2D NumPy array.
         # arr_2d = np.array([[1, 2, 3],
                  # [4, 5, 6],
                  # [7, 8, 9]])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]
print(element)

6


In [33]:
# Q 28:- Using boolean indexing, extract elements greater than 5 from the given NumPy array.
         #arr = np.array([3, 8, 2, 10, 5, 7])
arr = np.array([3, 8, 2, 10, 5, 7])

filtered_arr = arr[arr > 5]
print(filtered_arr)

[ 8 10  7]


In [34]:
# Q 29:- Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
         #arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6] 
print(sliced_arr)

[3 4 5 6]


In [35]:
# Q 30:-  Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
           #arr_2d = np.array([[1, 2, 3],
                 #  [4, 5, 6],
                  # [7, 8, 9]])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [2]:
# Q 31 :- Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
import numpy as np

def extract_elements_by_indices(arr, indices):
   
    indices = np.array(indices) 
    rows, cols = indices[:, 0], indices[:, 1]
    return arr[rows, cols]

array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

index_list = [(0, 2), (1, 1), (2, 0)]
result = extract_elements_by_indices(array_2d, index_list)
print(result)


[30 50 70]


In [3]:
# Q 32:- Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np

def filter_greater_than_threshold(arr, threshold):
   
    return arr[arr > threshold]

array_1d = np.array([5, 12, 7, 3, 18, 1, 9])
threshold_value = 8
result = filter_greater_than_threshold(array_1d, threshold_value)
print(result)


[12 18  9]


In [4]:
# Q 33 :- Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np

def extract_elements_from_3d(arr, idx1, idx2, idx3):
   
    idx1 = np.array(idx1)
    idx2 = np.array(idx2)
    idx3 = np.array(idx3)
    
    return arr[idx1, idx2, idx3]

array_3d = np.arange(3*4*5).reshape((3, 4, 5))

idx1 = [0, 1, 2]
idx2 = [1, 2, 3]
idx3 = [4, 0, 2]

result = extract_elements_from_3d(array_3d, idx1, idx2, idx3)
print(result)


[ 9 30 57]


In [5]:
# Q 34 :-  Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_elements_by_row_col(arr, row_indices, col_indices):
   
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    
    return arr[row_indices, col_indices]

array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

rows = [0, 1, 2]
cols = [2, 1, 0]

result = extract_elements_by_row_col(array_2d, rows, cols)
print(result)


[30 50 70]


In [7]:
# Q 35 :- Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [8]:
# Q 37 :-  Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 
#using NumPy broadcasting.import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = arr2 * arr1.T 

print(result)



[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [9]:
# Q 38:-  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

result = arr2 + arr1.T  

print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [10]:
# Q 39 :- Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

arr1 = np.array([[1],
                 [2],
                 [3]]) 

arr2 = np.array([[10, 20, 30]]) 

result = arr1 + arr2

print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [11]:
# Q 40 ;- . Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape
#incompatibility.
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]]) 

arr2 = np.array([[7, 8],
                 [9, 10]])

arr1_expanded = arr1[:, np.newaxis, :] 
arr2_expanded = arr2[:, :, np.newaxis] 

result = arr1_expanded * arr2_expanded

print(result)


[[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


In [12]:
# Q 41 :- Calculate column wise mean for the given array:
          #arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

col_mean = np.mean(arr, axis=0)

print(col_mean)


[2.5 3.5 4.5]


In [14]:
# Q 42 :-  Find maximum value in each row of the given array:
           #arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as n

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max = np.max(arr, axis=1)

print(row_max)

[3 6]


In [15]:
# Q 43 :- For the given array, find indices of maximum value in each column.
          #arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

col_max_indices = np.argmax(arr, axis=0)

print(col_max_indices)


[1 1 1]


In [17]:
# Q 44 :- For the given array, apply custom function to calculate moving sum along rows.
          #arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

def moving_sum(arr, window_size):
    result = np.zeros_like(arr, dtype=int)
    
    for i in range(arr.shape[0]): 
        for j in range(arr.shape[1]): 
            if j < window_size - 1:
                result[i, j] = np.sum(arr[i, :j+1])
            else:
                result[i, j] = np.sum(arr[i, j-window_size+1:j+1])
    
    return result

window_size = 2
result = moving_sum(arr, window_size)
print(result)


[[ 1  3  5]
 [ 4  9 11]]


In [18]:
# Q 45: -  In the given array, check if all elements in each column are even.
           #arr = np.array([[2, 4, 6], [3, 5, 7]])
import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even = np.all(arr % 2 == 0, axis=0)

print(all_even)

[False False False]


In [19]:
# Q 46 :- . Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
            #original_array = np.array([1, 2, 3, 4, 5, 6])
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2, 3 

reshaped_matrix = original_array.reshape(m, n)

print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [20]:
# Q 47:- Create a function that takes a matrix as input and returns the flattened array.
         #input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def flatten_matrix(matrix):
    
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [21]:
# Q 48 :-  Write a function that concatenates two given arrays along a specified axis.
           #array1 = np.array([[1, 2], [3, 4]])
           #array2 = np.array([[5, 6], [7, 8]])
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

result_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", result_axis_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [22]:
# Q 50 :-  Write a function that inserts and then deletes elements from a given array at specified indices.
           # original_array = np.array([1, 2, 3, 4, 5])
           # indices_to_insert = [2, 4]
           # values_to_insert = [10, 11]
           # indices_to_delete = [1, 3]
import numpy as np

def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    
    arr = np.insert(arr, indices_to_insert, values_to_insert)

    arr = np.delete(arr, indices_to_delete)

    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)


[ 1 10  4 11  5]


In [23]:
# Q 51;- Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between 
#`arr1` and `arr2`
import numpy as np

arr1 = np.random.randint(1, 21, size=(2, 5))

arr2 = np.arange(1, 11).reshape(2, 5)

result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)

arr1:
[[10  2 20  2  1]
 [12  6 15  7 13]]

arr2:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Result of element-wise addition:
[[11  4 23  6  6]
 [18 13 23 16 23]]


In [1]:
# Q 52 :-  Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integersfrom 1 to 10. Subtract `arr2`
#from `arr1` element-wise.
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [2]:
# Q 53:-  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication 
#between `arr1` and `arr2`.

arr1 = np.random.randint(0, 11, size=5)

arr2 = np.arange(1, 6)

result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [ 7  8 10  4  1]
arr2: [1 2 3 4 5]
Result: [ 7 16 30 16  5]


In [3]:
# Q 54 :-Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise 
#division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)

arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result: [2. 2. 2. 2. 2.]


In [4]:
# Q 55 :- Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
          #arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(arr, substring):
    return np.sum([s == substring for s in arr])

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

count = count_substring(arr, 'hello')

print("Count of 'hello':", count)

Count of 'hello': 3


In [5]:
# Q 56:- Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
         #arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

uppercase_arr = extract_uppercase(arr)

print("Uppercase characters:", uppercase_arr)

Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [7]:
# Q 58:- Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
         #arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)
                           
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

new_arr = replace_substring(arr, 'apple', 'orange')

print("Modified array:", new_arr)

Modified array: ['orange' 'banana' 'grape' 'pineorange']


In [8]:
# Q 59:- Write a function that concatenates strings in a NumPy array element-wise.
        #arr1 = np.array(['Hello', 'World'])
        #arr2 = np.array(['Open', 'AI'])

def concatenate_arrays(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_arrays(arr1, arr2)

print("Concatenated array:", result)

Concatenated array: ['HelloOpen' 'WorldAI']


In [9]:
# Q 61:-  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset 
#using NumPy's functions.

data = np.random.randint(1, 1001, size=100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print("Dataset:", data)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [ 55 963 333 760 311 281   5 400 308 179 572 874 369 162 265 781 986 819
 561 424 848 426 680 810 888 610 297 672 635 180 701 254  16 811 832 424
 211 755 669 954 746 977 835  28 212 111  90  24 118 316 367 564 757  23
 234 234 608 944 855 818 641 466 756 524 580 907 723  13 385 614 201 793
 304  28 662 456  45  51 847 571 413 338 503 523  15 728 691 173 609 275
 517 958 776 406 668 546 567 607 184 830]
Mean: 498.36
Median: 535.0
Variance: 82577.87039999999
Standard Deviation: 287.36365532196305


In [10]:
# Q 62:-  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

data = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Data:", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Data: [ 44  12  55  61  42  18  82  37  21  60  23  90  65  83 100  65   2  23
  70   7  30  43  47  61  98  15  90  47  80  12  85  40  37  88  30   9
  29  38  36  58  40  21 100  15  63  31  78  87  65  26]
25th Percentile: 26.75
75th Percentile: 68.75


In [11]:
# Q 63 ;- Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` 
#function.

x = np.random.randint(1, 100, size=10)
y = np.random.randint(1, 100, size=10)

correlation_matrix = np.corrcoef(x, y)

correlation_coefficient = correlation_matrix[0, 1]

print("x:", x)
print("y:", y)
print("Correlation Coefficient Matrix:\n", correlation_matrix)
print("Correlation Coefficient between x and y:", correlation_coefficient)

x: [18 82 87 44 58 95 71 93 72 48]
y: [35 90 74 33 43 26 82 15 22 55]
Correlation Coefficient Matrix:
 [[1.         0.09762238]
 [0.09762238 1.        ]]
Correlation Coefficient between x and y: 0.0976223797406611


In [12]:
# Q 65:-  Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third 
#quartiles.

data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)

quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print("Data:", data)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", quartile_1)
print("Third Quartile (75th Percentile):", quartile_3)

Data: [132 388 416 395 149 661 224 602 908 968  27 493 399 251 360 540 323 642
 485  91 350 656 405 867 817 748 856 200 221 512 252  78 166 508 105 889
 701 645 998 683 897 514  20 670 960 786 586 877 457 535]
10th Percentile: 129.3
50th Percentile (Median): 510.0
90th Percentile: 889.8
First Quartile (25th Percentile): 269.75
Third Quartile (75th Percentile): 696.5


In [13]:
# Q 67:-  Generate a random NumPy array and sort it in ascending order

data = np.random.randint(1, 101, size=20)

sorted_data = np.sort(data)

print("Original Array:", data)
print("Sorted Array:", sorted_data)

Original Array: [90 41 76 26 57  6 11 65 47  6 92 19 62  3 88 60 80 57 16 33]
Sorted Array: [ 3  6  6 11 16 19 26 33 41 47 57 57 60 62 65 76 80 88 90 92]


In [14]:
# Q 68:-  Filter elements >20  in the given NumPy array
          #arr = np.array([12, 25, 6, 42, 8, 30])

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Filtered Array (elements > 20):", filtered_arr)

Filtered Array (elements > 20): [25 42 30]


In [15]:
# Q 69:-  Filter elements which are divisible by 3 from a given NumPy array
          #arr = np.array([1, 5, 8, 12, 15])

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print("Filtered Array (elements divisible by 3):", filtered_arr)

Filtered Array (elements divisible by 3): [12 15]


In [16]:
# Q 70:- Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
         #arr = np.array([1, 2, 3])

arr = np.array([1, 2, 3])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_arr)

Filtered Array (elements ≥ 20 and ≤ 40): []


In [17]:
# Q 71 :-  For the given NumPy array, perform byte swapping in place using `byteswap()`.
           #arr = np.array([1, 2, 3], dtype=np.int32)

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(inplace=True)

print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [18]:
# q 74:- For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
         #arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = sys.byteorder
print("System endianness:", system_endianness)

if system_endianness == 'little':
    arr_swapped = arr.newbyteorder('>')
elif system_endianness == 'big':
    arr_swapped = arr.newbyteorder('<')

print("Original Array:", arr)
print("Array with swapped byte order:", arr_swapped)

System endianness: little
Original Array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [19]:
# Q 76 :-  For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
           #arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

array_byteorder = arr.dtype.byteorder
print("Array byteorder:", array_byteorder)

if array_byteorder == '=':
    print("No byte swapping needed. The array is in the system's native endianness.")
else:
    print("Byte swapping is necessary. The array is not in the system's native endianness.")

Array byteorder: =
No byte swapping needed. The array is in the system's native endianness.


In [20]:
# Q 77:- Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if
#modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [21]:
# Q 79:-Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, 1:3] 

view_b += 5

print("Original array (array_a):\n", array_a)
print("\nModified slice (view_b):\n", view_b)

Original array (array_a):
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]

Modified slice (view_b):
 [[10 11]
 [13 14]]


In [22]:
# Q 80:-Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in 
#`data_copy` and verify if it affects the original `data`.

data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5].copy()

data_copy[0] = 100

print("Original array (data):\n", data)
print("\nModified copy (data_copy):\n", data_copy)

Original array (data):
 [[10  8  7  2]
 [ 8  9 10  1]
 [ 3  7  4  3]]

Modified copy (data_copy):
 [100   8   7   8   9  10   7]


In [23]:
# Q 81:-  Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

addition_result = A + B
subtraction_result = A - B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition of A and B:\n", addition_result)
print("\nSubtraction of A and B:\n", subtraction_result)

Matrix A:
 [[7 3 6]
 [7 9 4]
 [2 9 4]]

Matrix B:
 [[4 8 1]
 [3 5 1]
 [1 8 6]]

Addition of A and B:
 [[11 11  7]
 [10 14  5]
 [ 3 17 10]]

Subtraction of A and B:
 [[ 3 -5  5]
 [ 4  4  3]
 [ 1  1 -2]]


In [24]:
# Q 82:- Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
import numpy as np

C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

result = np.dot(C, D)

print("Matrix C (3x2):\n", C)
print("\nMatrix D (2x4):\n", D)
print("\nMatrix multiplication result (C @ D):\n", result)

Matrix C (3x2):
 [[2 7]
 [4 2]
 [2 8]]

Matrix D (2x4):
 [[3 3 7 5]
 [7 8 3 6]]

Matrix multiplication result (C @ D):
 [[55 62 35 52]
 [26 28 34 32]
 [62 70 38 58]]


In [25]:
# Q 83:- Create a matrix `E` and find its transpose.

E = np.random.randint(1, 10, size=(3, 2))

E_transpose = E.T

print("Matrix E:\n", E)
print("\nTranspose of Matrix E:\n", E_transpose)

Matrix E:
 [[6 4]
 [6 2]
 [2 1]]

Transpose of Matrix E:
 [[6 6 2]
 [4 2 1]]


In [26]:
# Q 84:-  Generate a square matrix `F` and compute its determinant.

F = np.random.randint(1, 10, size=(3, 3))

determinant_F = np.linalg.det(F)

print("Matrix F:\n", F)
print("\nDeterminant of Matrix F:", determinant_F)

Matrix F:
 [[6 6 6]
 [7 5 2]
 [1 3 5]]

Determinant of Matrix F: 11.999999999999984


In [27]:
# Q 85:- Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 10, size=(3, 3))

determinant_G = np.linalg.det(G)

if determinant_G != 0:
    G_inverse = np.linalg.inv(G)
    print("Matrix G:\n", G)
    print("\nInverse of Matrix G:\n", G_inverse)
else:
    print("Matrix G is not invertible (determinant is zero).")

Matrix G:
 [[1 2 9]
 [4 5 5]
 [7 1 9]]

Inverse of Matrix G:
 [[-0.1659751   0.0373444   0.14522822]
 [ 0.00414938  0.22406639 -0.12863071]
 [ 0.12863071 -0.05394191  0.01244813]]
